use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "${SEARXNG_SECRET}"
  limiter: true

search:
  safe_search: 1
  formats:
    - html
    - json

ui:
  static_use_hash: true
